### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by iuchavez** [Adam01010101F/327_FTP_Client#1]
@tanmark927 It looks like something inside the change_to_passive() function is causing a segmentation fault when I run it.

https://github.com/Adam01010101F/327_FTP_Client/blob/26fe121ad3e9aafe7e9014a0cf808c700b75f106/ftpclient.cp#L160

**Comment by tanmark927** [comment]
When I ran the code, it executed without a segmentation fault. Perhaps this issue is due to the computer you used to run the program.
